"""
agent/tools.py - Tools available to the Software Architect Agent

WHY TOOLS EXIST:
  An LLM can only generate text. To interact with the real world (save files,
  read directories, etc.) it needs "tools" — Python functions the LLM can
  choose to call. LangChain's @tool decorator wraps a function so the LLM
  can discover and invoke it.

TOOLS IN THIS FILE:
  1. save_document    → Writes a markdown file to the user's chosen folder
                        AND indexes it in the vector store (long-term memory)
  2. list_documents   → Lists all .md files previously saved

HOW THE LLM CALLS TOOLS:
  1. LLM receives the tool schemas (name, description, parameters)
  2. LLM decides: "I need to save a file" → returns a tool_call object
  3. Our agent loop runs the tool function with the provided arguments
  4. The result is sent back to the LLM as a ToolMessage
  5. LLM generates its final response, now knowing the tool succeeded

VECTOR MEMORY INTEGRATION (NEW):
  After every successful file save, save_document() now also calls
  vector_memory.index_document(). This is the "write path" of our RAG system.
  Every document that lands on disk also lands in ChromaDB — automatically,
  with no extra action required from the LLM or the user.
"""

import os
import time
import logging
from datetime import datetime
from langchain_core.tools import tool

# Import the shared VectorMemory singleton.
# We use a lazy import inside the function body to avoid circular imports
# and to ensure the singleton is only created when actually needed.
from .vector_memory import get_vector_memory

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Global save path (set at runtime by the user, before agent starts)
# ─────────────────────────────────────────────────────────────────────────────
_save_path: str = "./output"


def set_save_path(path: str) -> None:
    """
    Set the directory where all documents will be saved.
    Called once at startup with the path the user provides.
    Creates the directory if it does not yet exist.
    """
    global _save_path
    _save_path = path
    os.makedirs(path, exist_ok=True)


def get_save_path() -> str:
    """Return the current save path (used by app.py for display)."""
    return _save_path


# ─────────────────────────────────────────────────────────────────────────────
# Tool Definitions
# ─────────────────────────────────────────────────────────────────────────────

@tool
def save_document(filename: str, content: str) -> str:
    """
    Save a markdown document to the user's output folder.

    Use this tool whenever the user asks you to CREATE, GENERATE, or WRITE a
    document (system design, API spec, database schema, sequence diagram, etc.).

    Args:
        filename: The file name for the document (e.g., 'system-design',
                  'api-spec-auth', 'user-service-erd'). The .md extension
                  will be added automatically if not present.
        content:  The full markdown content of the document.

    Returns:
        A confirmation string with the full absolute path of the saved file.
    """
    global _save_path
    start_time = time.time()

    logger.info(f"save_document called", extra={"saved_file": filename})

    # ── Sanitise filename ───────────────────────────────────────────────────
    clean_name = filename.strip().replace(" ", "-").lower()
    if not clean_name.endswith(".md"):
        clean_name += ".md"

    full_path = os.path.join(_save_path, clean_name)
    logger.debug(f"Target path: {full_path}")

    # ── Add a metadata comment at the top of every document ────────────────
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    header = f"<!-- Generated by Software Architect Agent | {timestamp} -->\n\n"

    # ── Write to disk ───────────────────────────────────────────────────────
    os.makedirs(_save_path, exist_ok=True)
    write_start = time.time()
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(header + content)
    write_duration = int((time.time() - write_start) * 1000)
    logger.info(f"File written", extra={"saved_file": clean_name, "duration_ms": write_duration})

    # ── Index in vector store (long-term memory) ────────────────────────────
    index_start = time.time()
    try:
        vm = get_vector_memory()
        chunk_count = vm.index_document(content, source_filename=clean_name)
        index_duration = int((time.time() - index_start) * 1000)
        logger.info(f"Vector indexing completed", extra={"saved_file": clean_name, "chunks": chunk_count, "duration_ms": index_duration})
        index_note = f" | Indexed {chunk_count} chunks in vector memory"
    except Exception as e:
        index_duration = int((time.time() - index_start) * 1000)
        logger.warning(f"Vector indexing failed: {e}", extra={"saved_file": clean_name, "duration_ms": index_duration})
        index_note = f" | Vector indexing skipped: {e}"

    total_duration = int((time.time() - start_time) * 1000)
    logger.info(f"save_document completed", extra={"saved_file": clean_name, "duration_ms": total_duration})

    return f"✅ Document saved: {os.path.abspath(full_path)}{index_note}"


@tool
def list_documents() -> str:
    """
    List all markdown (.md) documents that have been saved so far.

    Use this tool when the user asks to 'list', 'show', or 'see' their
    saved documents, or when they want to know what has been generated.

    Returns:
        A formatted list of saved documents with file sizes, or a message
        indicating no documents have been saved yet.
    """
    global _save_path

    logger.info("list_documents called")

    if not os.path.exists(_save_path):
        logger.warning(f"Save path does not exist: {_save_path}")
        return "📁 No documents saved yet. The output folder does not exist."

    md_files = sorted([f for f in os.listdir(_save_path) if f.endswith(".md")])

    if not md_files:
        logger.debug(f"No .md files found in: {_save_path}")
        return f"📁 No markdown documents found in: {os.path.abspath(_save_path)}"

    logger.info(f"Found {len(md_files)} documents")
    lines = [f"📁 Saved documents in: {os.path.abspath(_save_path)}\n"]
    for fname in md_files:
        fpath = os.path.join(_save_path, fname)
        size_kb = os.path.getsize(fpath) / 1024
        lines.append(f"  • {fname}  ({size_kb:.1f} KB)")

    return "\n".join(lines)
